import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={"px-6 bg-slate-200 space-y-4 " + inter.className}>
        <header>
          <div className='content'>
            <div>Logo</div>
            <nav className='flex gap-4'>
              <Link href='/'>Home</Link>
              <p>About</p>
              <p>Others</p>
              <p>Contribute</p>
            </nav>
          </div>
        </header>
        <>{children}</>
      </body>
    </html>
  );
}
